### ISSUE TITLE
Nntool requires scikit-image package 

### ISSUE THREAD

**Issue by EyssK** [GreenWaves-Technologies/gap_sdk#140]
The scikit-image seems to be required for nntool.
I just upgraded to the release-v3.5 tag from the release-v3.4 with ubuntu 18.04.

```
[usr@ubuntu1804 ~/gap_sdk]$ nntool                                                                                    
Traceback (most recent call last):                                                                                    
  File "/home/usr/gap_sdk/tools/nntool/nntool", line 99, in <module>                                                  
    main()                                                                                                            
  File "/home/usr/gap_sdk/tools/nntool/nntool", line 89, in main                         
    mod = importlib.import_module('interpreter.nntool_shell')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module             
    return _bootstrap._gcd_import(name[level:], package, level)                                                        
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import                         
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load                    
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                          
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                            
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module                                             
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                        
  File "/home/usr/gap_sdk/tools/nntool/interpreter/nntool_shell.py", line 19, in <module>                             
    from .commands.dump import DumpCommand, RoundingCommand                                                            
  File "/home/usr/gap_sdk/tools/nntool/interpreter/commands/dump.py", line 23, in <module>                            
    from execution.graph_executer import GraphExecuter                                                                
  File "/home/usr/gap_sdk/tools/nntool/execution/graph_executer.py", line 27, in <module>                              
    from quantization.float32.float_kernet_set import Float32KernelSet                                                
  File "/home/usr/gap_sdk/tools/nntool/quantization/float32/float_kernet_set.py", line 24, in <module>                 
    from quantization.float32.kernels.tensor_functions import (concat,                                                 
  File "/home/usr/gap_sdk/tools/nntool/quantization/float32/kernels/tensor_functions.py", line 17, in <module>        
    from skimage.transform import resize                   
ModuleNotFoundError: No module named 'skimage' 
```
No problem anymore after a 
```
pip3 install scikit-image
```

**Comment by PaulLuperini** [comment]
It is fixed in version 3.7.
`scikit-image` was added to `tools/nntool/requirement.txt`.
