### ISSUE TITLE
ImportError: cannot import name 'define' from 'attr'

### ISSUE THREAD

**Issue by paulxiongfree** [GreenWaves-Technologies/gap_sdk#263]
Hello,

I keep having this error when trying to compile example/nntool/mnist. Could you please help me with this? Thank you!

`Building GAP8 mode with 8 bit quantization
script model/nntool_script
GEN ... /home/paul/gap_sdk/tools/autotiler_v3/CNN_Generators/CNN_Generator_Util.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Generators/CNN_Copy_Generators.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Generators/SSD_Generators.c /home/paul/gap_sdk/tools/autotiler_v3/Generators/BilinearResizes/ResizeGenerator.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Generators_SQ8/CNN_Generators_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Generators_SQ8/RNN_Generators_SQ8.c
APP_SRCS... mnist.c BUILD_MODEL_SQ8BIT/mnistKernels.c /home/paul/gap_sdk/libs/gap_lib/img_io/ImgIO.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries/SSD_BasicKernels.c /home/paul/gap_sdk/tools/autotiler_v3/Generators/BilinearResizes/ResizeBasicKernels.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries/CNN_CopyBasicKernels.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_AT_Misc.c /home/paul/gap_sdk/tools/autotiler_v3/DSP_Libraries/math_funcs.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Activation_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Activation_HWC_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Bias_Linear_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Conv_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Pooling_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_Conv_DW_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_MatAlgebra_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/CNN_SoftMax_SQ8.c /home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8/RNN_SQ8.c
APP_CFLAGS... -DUSE_HYPER -g -O1 -mno-memcpy -fno-tree-loop-distribute-patterns -I. -I/home/paul/gap_sdk/libs/gap_lib/include -I/home/paul/gap_sdk/tools/autotiler_v3/Emulation -I/home/paul/gap_sdk/tools/autotiler_v3/Autotiler -I/home/paul/gap_sdk/tools/autotiler_v3/Generators/BilinearResizes -I/home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries -I/home/paul/gap_sdk/tools/autotiler_v3/DSP_Libraries -I/home/paul/gap_sdk/tools/autotiler_v3/CNN_Libraries_SQ8 -IBUILD_MODEL_SQ8BIT -DPERF -DAT_MODEL_PREFIX=mnist -DAT_INPUT_HEIGHT=28 -DAT_INPUT_WIDTH=28 -DAT_INPUT_COLORS=1 -DSTACK_SIZE=4028 -DSLAVE_STACK_SIZE=1024 -DAT_IMAGE=/home/paul/gap_sdk/examples/nntool/mnist/samples/5223_5.pgm
rm -f -rf BUILD_MODEL_SQ8BIT
echo "GENERATING INPUT IMAGES"
GENERATING INPUT IMAGES
(mkdir -p images; python3 model/save_samples.py -d images -n 5)
2021-08-10 23:19:00.008648: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/paul/gap_sdk/install/workstation/lib
2021-08-10 23:19:00.008699: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
mkdir BUILD_MODEL_SQ8BIT
cp model/mnist.tflite BUILD_MODEL_SQ8BIT/mnist.tflite
echo "GENERATING NNTOOL STATE FILE"
GENERATING NNTOOL STATE FILE
nntool -s model/nntool_script BUILD_MODEL_SQ8BIT/mnist.tflite 
Traceback (most recent call last):
  File "/home/paul/gap_sdk/tools/nntool/nntool", line 104, in <module>
    main()
  File "/home/paul/gap_sdk/tools/nntool/nntool", line 94, in main
    mod = importlib.import_module('interpreter.nntool_shell')
  File "/home/paul/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/paul/gap_sdk/tools/nntool/interpreter/nntool_shell.py", line 18, in <module>
    from .commands import *
  File "/home/paul/gap_sdk/tools/nntool/interpreter/commands/compile_at_model.py", line 19, in <module>
    from attr import define
ImportError: cannot import name 'define' from 'attr' (/home/paul/anaconda3/lib/python3.7/site-packages/attr/__init__.py)
../common/model_rules.mk:52: recipe for target 'BUILD_MODEL_SQ8BIT/mnist.json' failed
make: *** [BUILD_MODEL_SQ8BIT/mnist.json] Error 1
`

**Comment by afparsons** [comment]
I came across this error in a completely separate project. Do you know what the cause is?
