### ISSUE TITLE
KeyError or IndexError while trying to open quantized LSTM model with nntool

### ISSUE THREAD

**Issue by rallen10** [GreenWaves-Technologies/gap_sdk#265]
I am trying to open the attached LSTM model with nntool with command

[hello_lstm.zip](https://github.com/GreenWaves-Technologies/gap_sdk/files/7064472/hello_lstm.zip)

```bash
nntool
set debug true
open hello_lstm.tflite -q
```

but getting the error:
```bash
open - opening graph file model/gap8_build_hello_lstm/hello_lstm.tflite load_quantization = True
tflite - Importing TFLITE model version 3
Traceback (most recent call last):
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/cmd2.py", line 1661, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/cmd2.py", line 2081, in onecmd
    stop = func(statement)
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/decorators.py", line 223, in cmd_wrapper
    return func(cmd2_app, args)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/interpreter/commands/open.py", line 118, in do_open
    self.__open_graph(args)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/interpreter/commands/open.py", line 92, in __open_graph
    G = create_graph(graph_file, opts=opts)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/importer/importer.py", line 52, in create_graph
    graph = importer.create_graph(filename, opts)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/importer/tflite2/tflite.py", line 103, in create_graph
    self._import_tflite_graph(G, model, opts)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/importer/tflite2/tflite.py", line 154, in _import_tflite_graph
    self._provisional_outputs, opts)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/importer/tflite2/tflite.py", line 256, in _import_nodes
    G.quantization[NodeId(params)].out_qs[idx])
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/quantization_set.py", line 93, in __getitem__
    raise KeyError()
KeyError
EXCEPTION of type 'KeyError' occurred with message: ''
```

To the best of my knowledge, the `.tflite` model was already quantized when I converted it to tflite; however I have little TFLite experience and no experience quantizing models so I may have misunderstood what I was doing. I just followed [TFLite's instructions](https://www.tensorflow.org/lite/performance/post_training_quantization) and added to following line to my TFLite conversion script:
```
converter = tf.lite.TFLiteConverter.from_saved_model(tf_save_path)
# Perform quantization: https://www.tensorflow.org/lite/performance/post_training_quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
```
I don't have this error if I open the `hello_lstm.tflite` model without the `-q` flag, but then I can't `save_state` because I get:
```bash
EXCEPTION of type 'GraphNotReadyException' occurred with message: '
The opened graph must be quantized to use this command. Run the aquant command.'
```
I can't find enough documentation on `aquant` to perform the quantization within `nntool`; and anyway my model is trained on time-series data, not images, which seems to be the only data discussed for `aquant`

**Comment by rallen10** [comment]
Attempting to bump thread. I'm at a loss of how to resolve/workaround this issue

**Comment by rallen10** [comment]
Just a friendly bump. @sousoux I appreciate the help you've given in the past. Any insights on this error. Thank you for your time!

**Comment by rallen10** [comment]
Another friendly bump. Just trying to figure out how to get unstuck. Trying some of the other active developers I've seen in the issues: @Pafrak @Yaooooo

**Comment by sousoux** [comment]
To fix your latest issue please apply patch:

index 95de98b..634ea83 100644
--- a/importer/tflite2/common/tflite_node.py
+++ b/importer/tflite2/common/tflite_node.py
@@ -104,7 +104,7 @@ class TFLiteNode():
 
     def is_intermediate(self, input_idx):
         return (self._op.IntermediatesLength() > 0 and
-                bool(self._op.IntermediatesAsNumpy()[input_idx]))
+                input_idx in self._op.IntermediatesAsNumpy())
 
     def get_options(self, options_class):
         if self._op.BuiltinOptions():

Can you provide the graph that caused the first issue. This patch will be in out next release. Sorry for the trouble and the slow answer.

**Comment by rallen10** [comment]
@sousoux Thank you for the patch. I applied it with the following commands after copying it to a file `gap_sdk/tools/nntool/tflite_node.diff`

```
cd gap_sdk/tools/nntool
patch -p1 < ./tflite_node.diff
```

This successfully moved past the [`IndexError`](https://github.com/GreenWaves-Technologies/gap_sdk/issues/265#issuecomment-916396427) but now I am hitting a value error when trying to run `open model/gap8_build_hello_lstm/hello_lstm.tflite -q` on the following model that was [integer-only quantized with TFLite](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization):

[hello_lstm.zip](https://github.com/GreenWaves-Technologies/gap_sdk/files/7178784/hello_lstm.zip)

```
Welcome to NNTOOL. Type help or ? to list commands.

settings - set log level to INFO
log_level - was: 'INFO'
now: 'INFO'
(NNT) set debug true
debug - was: False
now: True
(NNT) open model/gap8_build_hello_lstm/hello_lstm.tflite -q
open - opening graph file model/gap8_build_hello_lstm/hello_lstm.tflite load_quantization = True
tflite - Importing TFLITE model version 3
nngraph - update graph dimensions
set_aliases - looking for aliased edges
nngraph - calculate liveness
nngraph - update graph dimensions
set_aliases - looking for aliased edges
nngraph - calculate liveness
unified_quantizer - forwards input_1 in:  out: None stop [] fusion False
unified_quantizer - handler FromStatsMult selected for InputParameters(input_1)
unified_quantizer - forwards handler input_1 returned in:  out: -1.01<(i8-0.00)*0.00790489<1.00 fusion False
unified_quantizer - forwards finished in edges input_1
unified_quantizer - forwards at input_1 on out edge 0
unified_quantizer - forwards i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.45<(i8-0.00)*0.00352488<0.45 fusion False
unified_quantizer - forwards finished in edges i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.51<(i8-0.00)*0.00401241<0.51 fusion False
unified_quantizer - forwards finished in edges i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -1.51<(i8-0.00)*0.01182634<1.50 fusion False
unified_quantizer - forwards finished in edges i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -2.36<(i8-0.00)*0.01845481<2.34 fusion False
unified_quantizer - forwards finished in edges i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.43<(i8-0.00)*0.00335199<0.43 fusion False
unified_quantizer - forwards finished in edges r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.49<(i8-0.00)*0.00381458<0.48 fusion False
unified_quantizer - forwards finished in edges r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.68<(i8-0.00)*0.00530595<0.67 fusion False
unified_quantizer - forwards finished in edges r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -1.70<(i8-0.00)*0.01328644<1.69 fusion False
unified_quantizer - forwards finished in edges r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -59369.58<(i32-0.00)*0.00002765<59369.58 fusion False
unified_quantizer - forwards finished in edges i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -67581.05<(i32-0.00)*0.00003147<67581.05 fusion False
unified_quantizer - forwards finished in edges f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -199191.16<(i32-0.00)*0.00009276<199191.16 fusion False
unified_quantizer - forwards finished in edges c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -310834.59<(i32-0.00)*0.00014474<310834.59 fusion False
unified_quantizer - forwards finished in edges o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -1.01<(i8-0.00)*0.00787402<1.00 fusion False
unified_quantizer - forwards finished in edges i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -1.01<(i8-0.00)*0.00787402<1.00 fusion False
unified_quantizer - forwards finished in edges c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in: -1.01<(i8-0.00)*0.00790489<1.00,-0.45<(i8-0.00)*0.00352488<0.45,-0.51<(i8-0.00)*0.00401241<0.51,-1.51<(i8-0.00)*0.01182634<1.50,-2.36<(i8-0.00)*0.01845481<2.34,-0.43<(i8-0.00)*0.00335199<0.43,-0.49<(i8-0.00)*0.00381458<0.48,-0.68<(i8-0.00)*0.00530595<0.67,-1.70<(i8-0.00)*0.01328644<1.69,None,None,None,-59369.58<(i32-0.00)*0.00002765<59369.58,-67581.05<(i32-0.00)*0.00003147<67581.05,-199191.16<(i32-0.00)*0.00009276<199191.16,-310834.59<(i32-0.00)*0.00014474<310834.59,None,None,-1.01<(i8-0.00)*0.00787402<1.00,-1.01<(i8-0.00)*0.00787402<1.00 out: None stop [] fusion False
unified_quantizer - handler LSTMMultMult8x8 selected for LSTMParameters(UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
Traceback (most recent call last):
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/cmd2.py", line 1661, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/cmd2.py", line 2081, in onecmd
    stop = func(statement)
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/decorators.py", line 223, in cmd_wrapper
    return func(cmd2_app, args)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/interpreter/commands/open.py", line 122, in do_open
    self.__open_graph(args)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/interpreter/commands/open.py", line 96, in __open_graph
    G = create_graph(graph_file, opts=opts)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/importer/importer.py", line 52, in create_graph
    graph = importer.create_graph(filename, opts)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/importer/tflite2/tflite.py", line 137, in create_graph
    G.quantization = quantizer.quantize(G, start_nodes=nodes_with_bad_quantization, force_all=True)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 887, in quantize
    raise ex
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 884, in quantize
    self.quantize_forwards(G, state, params, **quant_kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 472, in quantize_forwards
    force_all=force_all, **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 484, in go_forward
    force_all=force_all, **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 420, in quantize_forwards
    **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 308, in handle
    return handler.quantize(params, in_qs, stats, fusion=parent_params, **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantization_handler.py", line 119, in quantize
    return cls._quantize(params, in_qs, stats, **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/multiplicative/quantizers/lstm_mult_8_8.py", line 77, in _quantize
    cls.check_valid_ranges(params, stats, idx=0, dirs='out')
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantization_handler.py", line 64, in check_valid_ranges
    f'no valid range information for node {params.name}. Graph cannot be quantized.')
ValueError: no valid range information for node UNIDIRECTIONAL_SEQUENCE_LSTM_0_1. Graph cannot be quantized.
EXCEPTION of type 'ValueError' occurred with message: 'no valid range information for node UNIDIRECTIONAL_SEQUENCE_LSTM_0_1. Graph cannot be quantized.'
```

It seems that the error may be on quantization and conversion with TFLite, however I can successfully run inference on the quantized model before attempting to open with nntool, therefore I'm not sure how to debug what the quantization issue is with nntool (note that I have very limited experience with TFLite conversion and model quantization).

**Comment by rallen10** [comment]
@sousoux As for the graph that caused the first KeyError issue, it is attached in the first comment: https://github.com/GreenWaves-Technologies/gap_sdk/issues/265#issue-980893644

Note that graph was [dynamic range quantized](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization) whereas the later graph that encountered the `IndexError` and then `ValueError` was integer-only quantized

**Comment by sousoux** [comment]
@rallen10 

Sorry. Only just saw this. I'll take a look. Quantized LSTM via tflite must be a new feature. They couldn't do it before. Maybe they are missing some activation range information that we need to reconstruct.

**Comment by sousoux** [comment]
Confirmed. Current nntool does not support importing quantization on RNN/LSTM layers. I have added this and it will be in our next release.

**Comment by rallen10** [comment]
@sousoux I really appreciate all of the help. If it helps I can close this issue and open another since this seems to be a separate issue all together
