### ISSUE TITLE
ValueError no valid range when importing quantized LSTM with nntool

### ISSUE THREAD

**Issue by rallen10** [GreenWaves-Technologies/gap_sdk#277]
For context see issue: https://github.com/GreenWaves-Technologies/gap_sdk/issues/265

When attempting to open the attached LSTM model that was integer-only quantized with TFLite, I receive the following error

[hello_lstm.zip](https://github.com/GreenWaves-Technologies/gap_sdk/files/7178784/hello_lstm.zip)

```
Welcome to NNTOOL. Type help or ? to list commands.

settings - set log level to INFO
log_level - was: 'INFO'
now: 'INFO'
(NNT) set debug true
debug - was: False
now: True
(NNT) open model/gap8_build_hello_lstm/hello_lstm.tflite -q
open - opening graph file model/gap8_build_hello_lstm/hello_lstm.tflite load_quantization = True
tflite - Importing TFLITE model version 3
nngraph - update graph dimensions
set_aliases - looking for aliased edges
nngraph - calculate liveness
nngraph - update graph dimensions
set_aliases - looking for aliased edges
nngraph - calculate liveness
unified_quantizer - forwards input_1 in:  out: None stop [] fusion False
unified_quantizer - handler FromStatsMult selected for InputParameters(input_1)
unified_quantizer - forwards handler input_1 returned in:  out: -1.01<(i8-0.00)*0.00790489<1.00 fusion False
unified_quantizer - forwards finished in edges input_1
unified_quantizer - forwards at input_1 on out edge 0
unified_quantizer - forwards i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.45<(i8-0.00)*0.00352488<0.45 fusion False
unified_quantizer - forwards finished in edges i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.51<(i8-0.00)*0.00401241<0.51 fusion False
unified_quantizer - forwards finished in edges i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -1.51<(i8-0.00)*0.01182634<1.50 fusion False
unified_quantizer - forwards finished in edges i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -2.36<(i8-0.00)*0.01845481<2.34 fusion False
unified_quantizer - forwards finished in edges i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.43<(i8-0.00)*0.00335199<0.43 fusion False
unified_quantizer - forwards finished in edges r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at r_2_i_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.49<(i8-0.00)*0.00381458<0.48 fusion False
unified_quantizer - forwards finished in edges r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at r_2_f_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -0.68<(i8-0.00)*0.00530595<0.67 fusion False
unified_quantizer - forwards finished in edges r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at r_2_c_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -1.70<(i8-0.00)*0.01328644<1.69 fusion False
unified_quantizer - forwards finished in edges r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at r_2_o_w_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -59369.58<(i32-0.00)*0.00002765<59369.58 fusion False
unified_quantizer - forwards finished in edges i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -67581.05<(i32-0.00)*0.00003147<67581.05 fusion False
unified_quantizer - forwards finished in edges f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at f_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -199191.16<(i32-0.00)*0.00009276<199191.16 fusion False
unified_quantizer - forwards finished in edges c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at c_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -310834.59<(i32-0.00)*0.00014474<310834.59 fusion False
unified_quantizer - forwards finished in edges o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at o_b_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -1.01<(i8-0.00)*0.00787402<1.00 fusion False
unified_quantizer - forwards finished in edges i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at i_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in:  out: None stop [] fusion False
unified_quantizer - handler ConstantInputMult selected for ConstantInputParameters(c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
unified_quantizer - forwards handler c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 returned in:  out: -1.01<(i8-0.00)*0.00787402<1.00 fusion False
unified_quantizer - forwards finished in edges c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1
unified_quantizer - forwards at c_state_UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 on out edge 0
unified_quantizer - forwards UNIDIRECTIONAL_SEQUENCE_LSTM_0_1 in: -1.01<(i8-0.00)*0.00790489<1.00,-0.45<(i8-0.00)*0.00352488<0.45,-0.51<(i8-0.00)*0.00401241<0.51,-1.51<(i8-0.00)*0.01182634<1.50,-2.36<(i8-0.00)*0.01845481<2.34,-0.43<(i8-0.00)*0.00335199<0.43,-0.49<(i8-0.00)*0.00381458<0.48,-0.68<(i8-0.00)*0.00530595<0.67,-1.70<(i8-0.00)*0.01328644<1.69,None,None,None,-59369.58<(i32-0.00)*0.00002765<59369.58,-67581.05<(i32-0.00)*0.00003147<67581.05,-199191.16<(i32-0.00)*0.00009276<199191.16,-310834.59<(i32-0.00)*0.00014474<310834.59,None,None,-1.01<(i8-0.00)*0.00787402<1.00,-1.01<(i8-0.00)*0.00787402<1.00 out: None stop [] fusion False
unified_quantizer - handler LSTMMultMult8x8 selected for LSTMParameters(UNIDIRECTIONAL_SEQUENCE_LSTM_0_1)
Traceback (most recent call last):
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/cmd2.py", line 1661, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/cmd2.py", line 2081, in onecmd
    stop = func(statement)
  File "/home/ross/miniconda3/envs/hello_ncp/lib/python3.7/site-packages/cmd2/decorators.py", line 223, in cmd_wrapper
    return func(cmd2_app, args)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/interpreter/commands/open.py", line 122, in do_open
    self.__open_graph(args)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/interpreter/commands/open.py", line 96, in __open_graph
    G = create_graph(graph_file, opts=opts)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/importer/importer.py", line 52, in create_graph
    graph = importer.create_graph(filename, opts)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/importer/tflite2/tflite.py", line 137, in create_graph
    G.quantization = quantizer.quantize(G, start_nodes=nodes_with_bad_quantization, force_all=True)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 887, in quantize
    raise ex
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 884, in quantize
    self.quantize_forwards(G, state, params, **quant_kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 472, in quantize_forwards
    force_all=force_all, **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 484, in go_forward
    force_all=force_all, **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 420, in quantize_forwards
    **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantizer.py", line 308, in handle
    return handler.quantize(params, in_qs, stats, fusion=parent_params, **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantization_handler.py", line 119, in quantize
    return cls._quantize(params, in_qs, stats, **kwargs)
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/multiplicative/quantizers/lstm_mult_8_8.py", line 77, in _quantize
    cls.check_valid_ranges(params, stats, idx=0, dirs='out')
  File "/home/ross/Projects/AIIA/crazyflie/gap_sdk/tools/nntool/quantization/unified_quantization_handler.py", line 64, in check_valid_ranges
    f'no valid range information for node {params.name}. Graph cannot be quantized.')
ValueError: no valid range information for node UNIDIRECTIONAL_SEQUENCE_LSTM_0_1. Graph cannot be quantized.
EXCEPTION of type 'ValueError' occurred with message: 'no valid range information for node UNIDIRECTIONAL_SEQUENCE_LSTM_0_1. Graph cannot be quantized.'
```

**Comment by rallen10** [comment]
The [v4.7.0 release](https://github.com/GreenWaves-Technologies/gap_sdk/releases/tag/release-v4.7.0) seems to have fixed this!
