### ISSUE TITLE
unable to make sdk with gapuino model 1

### ISSUE THREAD

**Issue by JJunHan** [GreenWaves-Technologies/gap_sdk#303]
Hi!

I have a gapuino development board (model 1 as printed on the back) and i followed the instructions in this sdk repo. after sourcing the sourceme.sh file, i selected option 7 : - GAPUINO. i tried to do 'make help' but an error: 'make: *** No rule to make target 'help'.  Stop.' occurs. 

When i try to 'make all' or 'make sdk' i get this error message:

`
make[3]: Entering directory '/home/osboxes/gap_sdk/gap8/rtos/pulp/archi_pulp'
scons
scons: Reading SConscript files ...
b'\x1b[91mFATAL ERROR: \x1b[0mExpecting property name enclosed in double quotes: line 14 column 7 (char 274)\n'
CalledProcessError: Command '['plpfiles', 'copy', '--item=archi_files']' returned non-zero exit status 255.:
  File "/home/osboxes/gap_sdk/gap8/rtos/pulp/archi_pulp/SConstruct", line 21:
    for file in subprocess.check_output(shlex.split('plpfiles copy --item=archi_files')).decode('UTF-8').split():
  File "/usr/lib/python3.8/subprocess.py", line 415:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516:
    raise CalledProcessError(retcode, process.args,
make[3]: *** [Makefile:2: build] Error 2
make[3]: Leaving directory '/home/osboxes/gap_sdk/gap8/rtos/pulp/archi_pulp'
make[2]: *** [Makefile:7: do.archi] Error 2
make[2]: Leaving directory '/home/osboxes/gap_sdk/gap8/rtos/pulp'
make[1]: *** [gap8/gap8.mk:115: pulp-os] Error 2
make[1]: Leaving directory '/home/osboxes/gap_sdk'
make: *** [Makefile:42: all] Error 2
`
However, if i change to option 10: 10 - GAPUINO_V3, i am able to execute 'make all' but the hello world application results in an error (which i think is because the version dont match):

`
DEPRECATED! use 'adapter driver' not 'interface'
DEPRECATED! use 'adapter speed' not 'adapter_khz'
DEPRECATED! use 'adapter driver' not 'interface'
TARGET create
0
GAP8 INIT TARGET
GAP8 examine target
Init jtag
Initialising GAP8 JTAG TAP
Error: timed out while waiting for target halted

Traceback (most recent call last):
  File "/home/osboxes/gap_sdk/utils/gapy/gapy", line 162, in <module>
    main()
  File "/home/osboxes/gap_sdk/utils/gapy/gapy", line 152, in main
    operationFunc(args, config, system)
  File "/home/osboxes/gap_sdk/utils/gapy/run.py", line 189, in operationFunc
    raise RuntimeError('Runner has failed with value: %d' % status)
RuntimeError: Runner has failed with value: -1
make: *** [/home/osboxes/gap_sdk/rtos/freeRTOS/vendors/gwt/rules/freeRTOS_rules.mk:418: run] Error 1
`

any help would be appreciated.

**Comment by JJunHan** [comment]
@fernandoFernandeSantos HI, I believe the new sdk version doesn't support gapuino v1.
