### ISSUE TITLE
nn_menu, mobilenetv1 dumping to GAP8

### ISSUE THREAD

**Issue by berab** [GreenWaves-Technologies/gap_sdk#306]
Hi,

When I run the command :
`python3 dump_mobilenet_to_GAP8.py --ckp_file './fake_quant_models/imagenet/mobilenetv1_224_1.0/checkpoint.pth.tar' --img_file './image144.jpeg'`

I get the following error:

```
 ************
input/x.1
IO Node
************
output/output.1
IO Node
Traceback (most recent call last):
  File "/mnt/studproj/kilic/MobilenetV1_Pytorch/dump_mobilenet_to_GAP8.py", line 541, in <module>
    main()
  File "/mnt/studproj/kilic/MobilenetV1_Pytorch/dump_mobilenet_to_GAP8.py", line 123, in main
    quantizer = quantization.QuantOp(model, quant_type = type_quant, weight_bits = weight_bits,bias_bits =32, \
  File "/mnt/studproj/kilic/MobilenetV1_Pytorch/training/quantization/quantop.py", line 364, in __init__
    v = replace_graph[n]
KeyError: 'model.0.0'
```

Anyone has an idea how to handle the issue? Thanks.

Best regards,
Beran

**Comment by mrusci** [comment]
The issue may be due to a mismatch of PyTorch (onnx) package versions. In particular, the code was tested on PyTorch 1.1, as indicated in the training README. Can you try this version?

**Comment by berab** [comment]
Thanks a lot @mrusci, installing pytorch 1.1 worked.
