### ISSUE TITLE
load pre-quantized tflite model error

### ISSUE THREAD

**Issue by aqqz** [GreenWaves-Technologies/gap_sdk#327]
When I load a pre-quantized tflite model, I miss this error:

```bash
(NNT) set debug true
debug - was: False
now: True
(NNT) open model/voc.tflite -q
open - opening graph file model/voc.tflite load_quantization = True
tflite - Importing TFLITE model version 3
Traceback (most recent call last):
  File "/home/taozhi/anaconda3/envs/gapsdk/lib/python3.8/site-packages/cmd2/cmd2.py", line 1661, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/home/taozhi/anaconda3/envs/gapsdk/lib/python3.8/site-packages/cmd2/cmd2.py", line 2081, in onecmd
    stop = func(statement)
  File "/home/taozhi/anaconda3/envs/gapsdk/lib/python3.8/site-packages/cmd2/decorators.py", line 223, in cmd_wrapper
    return func(cmd2_app, args)
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/interpreter/commands/open.py", line 183, in do_open
    self.__open_graph(args)
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/interpreter/commands/open.py", line 158, in __open_graph
    self.open_graph(graph_file, **opts)
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/interpreter/commands/open.py", line 191, in open_graph
    G = create_graph(file_path, opts=kwargs)
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/importer/importer.py", line 53, in create_graph
    graph = importer.create_graph(filename, opts)
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/importer/tflite2/tflite.py", line 99, in create_graph
    self._import_tflite_graph(G, model, opts)
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/importer/tflite2/tflite.py", line 151, in _import_tflite_graph
    self._import_nodes(G, graph, handlers, all_nodes,
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/importer/tflite2/tflite.py", line 240, in _import_nodes
    params = handler.handle(
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/importer/tflite2/handlers/handler.py", line 67, in handle
    return ver_handle(node, **kwargs)
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/importer/tflite2/handlers/backend/fully_connected.py", line 152, in version_1
    return cls._common(node, **kwargs)
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/importer/tflite2/handlers/backend/fully_connected.py", line 127, in _common
    cls.new_load_filter_parameters(G, params, params.filter.actual_shape, params.filter.get_order_idx('out_c'),
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/importer/tflite2/handlers/backend/filter_mixin.py", line 151, in new_load_filter_parameters
    mulbiases_q = MultMulBiasScaleQType.from_filter(
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/quantization/multiplicative/scaling_qtypes.py", line 133, in from_filter
    qtype = cls(dtype=dtype,
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/quantization/multiplicative/scaling_qtypes.py", line 127, in __init__
    self.scale = scale
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/quantization/multiplicative/scaling_qtypes.py", line 177, in scale
    self.compute_scales()
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/quantization/multiplicative/scaling_qtypes.py", line 186, in compute_scales
    self._qbiases, self._qnorms = compute_scales(self.scale,
  File "/home/taozhi/projects/gap/gap_sdk/tools/nntool/quantization/multiplicative/utils/scale.py", line 35, in compute_scales
    max_val = np.power(2, max_bits)
ValueError: Integers to negative integer powers are not allowed.
EXCEPTION of type 'ValueError' occurred with message: 'Integers to negative integer powers are not allowed.'
```

and this is my quantized code:

```python
model = tf.keras.models.load_model(model_path)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    if quantization=='int8':
        print("quantizing model by int8...\n")
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_data_gen
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.target_spec.supported_types = [tf.int8]
        converter.inference_input_type = tf.uint8
        converter.inference_output_type = tf.uint8
    print("converting model...\n")
    tflite_model = converter.convert()  

    with open(save_path, "wb") as f:
        f.write(tflite_model)
```
is there any wrong with it?

**Comment by aqqz** [comment]
I find the code here ,the `available_bits` go in to -1. I don`t understand here, but I find to normal model it is over 0.
code:
```
if not isinstance(scale, np.ndarray):
        scale = np.array([scale], dtype=np.float32)
    iinfo = np.iinfo(dtype)
    signed = iinfo.min < 0
    max_bits = iinfo.bits - (1 if signed else 0)
    print("available_bits: ", available_bits)
    if available_bits is not None:
        max_bits = min(max_bits, available_bits)
    print("max_bit: ", max_bits)
    bits = np.full(scale.shape, max_bits)
    factors = np.array([math.frexp(scale) for scale in scale],
                       dtype=[("scale", "f4"), ("norm", "i1")])

    max_val = np.power(2, max_bits)
```
result:
```bash
(NNT) open model/voc_q.tflite -q
open - opening graph file model/voc_q.tflite load_quantization = True
tflite - Importing TFLITE model version 3
quantize_mixin - removing (de)quantize node QUANTIZE_0_0 with no effect
available_bits:  13
max_bit:  8
available_bits:  8
max_bit:  8
available_bits:  -1
max_bit:  -1
EXCEPTION of type 'ValueError' occurred with message: 'Integers to negative integer powers are not allowed.'
```

**Comment by aqqz** [comment]
after change model structer , I fix this problem , but I don`t know where is wrong:
before:

```python
def net(input, num_classes):
    x = Conv2D(32, (3, 3), padding="same")(input)
    x = BatchNormalization()(x)
    x = ReLU()(x)
    x = MaxPooling2D(2, 2)(x)

    x = Conv2D(64, (3, 3), padding="same")(x)
    x = BatchNormalization()(x)
    x = ReLU()(x)
    x = MaxPooling2D(2, 2)(x)

    x = Flatten()(x)
    x = Dense(num_classes, activation="softmax")(x)
    return x
```

after:

```python
def net(input, num_classes):
    x = Conv2D(32, (3, 3), padding="same")(input)
    # x = BatchNormalization()(x)
    x = ReLU()(x)
    x = MaxPooling2D(2, 2)(x)
    
    x = Conv2D(64, (3, 3), padding="same")(x)
    # x = BatchNormalization()(x)
    x = ReLU()(x)
    x = MaxPooling2D(2, 2)(x)
    
    x = Conv2D(64, (3, 3), padding="same")(x)
    # x = BatchNormalization()(x)
    x = ReLU()(x)
    x = MaxPooling2D(2, 2)(x)
    x = Flatten()(x)
    x = Dense(num_classes, activation="softmax")(x)
    return x
```
yes, I just add a conv layer and remove the bn layers

**Comment by aqqz** [comment]
I think it may be the params count to large
