### ISSUE TITLE
Autotiler: Does Autotiler have any requirements for the onnx model structure?

### ISSUE THREAD

**Issue by ChenMathilda** [GreenWaves-Technologies/gap_sdk#372]
Hi, 
I made some changes to the model of Dronet-v2 and generated the following onnx model:
![VhPnjrMtkb](https://user-images.githubusercontent.com/61350967/219940816-d895a507-71c1-4853-8de9-774aa835c8c1.png)
An output item was added to the Dronet-v2.
![image](https://user-images.githubusercontent.com/61350967/219941017-a6305605-2b1e-4483-a291-9306c4411631.png)
But I met this Error when I try to generate .c file:
```
generator - Saving model to nntool_output/networkModel.c
Traceback (most recent call last):
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/scripts/nntool", line 107, in <module>
    main()
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/scripts/nntool", line 89, in main
    mod.generate_code(args)
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/nntool/interpreter/generator.py", line 93, in generate_code
    write_template(G, code_gen, opts['model_directory'], opts['model_file'], code_template, "model")
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/nntool/interpreter/generator.py", line 48, in write_template
    model = template(G, code_generator=code_gen)
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/nntool/generation/default_template.py", line 198, in default_template
    return execute_template(generator_template_v3, G, naming_convension, code_generator)
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/nntool/generation/default_template.py", line 192, in execute_template
    return template_function(G, code_generator)
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/nntool/generation/default_template.py", line 93, in generator_template_v3
    ${gen.kernel_generator(indent=1)}
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/nntool/generation/code_generator.py", line 541, in kernel_generator
    if not self.new_execute_phase("kernels", node, qrec,
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/nntool/generation/generators/generator_helpers.py", line 81, in new_execute_phase
    this_res = getattr(gen_class, PHASE_METHODS[phase_name])(self, param, qrec, *args, **kwargs)
  File "/home/chennaiting/pulp/pulp-dronet/gap_sdk/tools/nntool/nntool/generation/generators/general/copy_parameters.py", line 51, in kernel_generator
    raise ValueError(
ValueError: Cannot generate strided slice layer _Gather_1 with a copy if start != 0
make: *** [common/model_rules.mk:49: nntool_output/networkModel.c] Error 1
```
It seems that Autotiler cannot tile this onnx model.
If it is true that Autotiler cannot tile this kind of network structure, what changes should I make to the Dronet-v2's structure?
Hope to get reply,thanks!

**Comment by sousoux** [comment]
Don't use gather. It is a non uniform operator (even if you are using it in a uniform way). Use a split/slice if you want to do something like that. We may support certain gathers in the future however we will probably never be able to completely support it for any size of input and in many cases it will be highly inefficient.
